wandb_version: 1

epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721021416
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.17.3
      8:
      - 3
      - 5
      13: windows-amd64
