wandb:
  project: "MEG-classification"
  comment: "被験者ID注入"

dry_run: False
use_wandb: True
# use_pin_memory: True
# use_non_blocking: True
use_amp: True
use_multi_seeds: False
device: cuda:0
num_workers: 4
seed: 3711
num_classes: 1854
num_subjects: 4
# num_epochs: 20
num_epochs: 200
# num_batches: 32
num_batches: 128
# num_batches: 256
learning_rate: 0.001
num_patience: 30


# データセット
data_dir: data
data_augmentation_train: False
data_augmentation_test: False
augmentation_prob: 0.2

# 前処理
use_resampling: False
force_preprocess: False
current_rate: 281
lowcut: 0.5
highcut: 50
target_rate: 128
num_channels: 271  # チャンネル数
num_timepoints: 128
fs: 128
use_baseline_correction: False

# 交差検証
splitter_name: KFold
use_cv: False
n_splits: 5

optimizer: AdamW
scheduler: CosineLRScheduler
t_initial: 100
lr_min: 0.00005
warmup_t: 2
warmup_lr_init: 0.0005


model_name: 
selected_model_index: 7
model:
  - name: "EEGNet"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
  - name: "EEGNetImproved"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
  - name: "EEGNetWithSubject"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNorm"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNormAll"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNormAll3"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.6
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNormAll3SubjectInjection"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetGRU"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.4
      num_subjects: 4
  - name: "ImprovedEEGNet"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.2
      num_subjects: 4
  - name: "ImprovedEEGNet2"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "ImprovedEEGNet3"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  # - name: "EEGNetWithAttention"
  #   params:
  #     num_classes: 1854
  #     Chans: 271
  #     Samples: 128
  #     dropout_rate: 0.5



# Evaluation
model_path: 