wandb:
  project: "MEG-classification"
  comment: "EEGNetWithSubjectBatchNormAdd"

dry_run: False
use_wandb: True
device: cuda:0
num_workers: 4
seed: 3711
num_classes: 1854
num_subjects: 4
num_epochs: 50
num_batches: 32
learning_rate: 0.001
num_patience: 7


# データセット
data_dir: data
data_augmentation_train: False
data_augmentation_test: False
augmentation_prob: 0.2

# 前処理
force_preprocess: False
current_rate: 281
lowcut: 0.5
highcut: 50
target_rate: 128
num_channels: 271  # チャンネル数
num_timepoints: 128
fs: 128

# 交差検証
splitter_name: KFold
use_cv: False
n_splits: 5

optimizer: AdamW
scheduler: ReduceLROnPlateau

model_name: EEGNetWithSubjectBatchNormAdd
selected_model_index: 3
model:
  - name: "EEGNet"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
  - name: "EEGNetImproved"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
  - name: "EEGNetWithSubject"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNorm"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNormAll"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4
  - name: "EEGNetWithSubjectBatchNormAll3"
    params:
      num_classes: 1854
      Chans: 271
      Samples: 128
      dropout_rate: 0.5
      num_subjects: 4

  # - name: "EEGNetWithAttention"
  #   params:
  #     num_classes: 1854
  #     Chans: 271
  #     Samples: 128
  #     dropout_rate: 0.5



# Evaluation
model_path: 